[carbon]
plan_path = "carbon"

[carbon-cache]
plan_path = "carbon-cache"

[graphite-web]
plan_path = "graphite-web"

[inspec]
plan_path = "inspec"

[openssl]
plan_path = "openssl"

[openssl-fips]
plan_path = "openssl-fips"
