- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.1.1
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: git://github.com/detailyang/pre-commit-shell
  rev: 1.0.2
  hooks:
    - id: shell-lint
      args: ["--exclude=SC2034,SC2148,SC2154"]
- repo: local
  hooks:
    - id: check-default-variables
      name: Check for Habitat default plan variables
      entry: ./test/check-default-variables.sh
      language: system
      files: plan.sh$
    - id: check-bldr-toml
      name: Check for an entry in .bldr.toml
      entry: ./test/check-bldr-toml.sh
      language: system
      files: plan.sh$
    - id: check-bad-patterns
      name: Check for bad patterns in Hook files
      entry: ./test/check-bad-patterns.sh
      language: system
      files: hooks/*
