language: ruby
rvm: system

branches:
  only:
    - master

sudo: required

services:
  - docker

install: skip

env:
  matrix:
    - HAB_PLAN=
    - HAB_PLAN=carbon
    - HAB_PLAN=carbon-cache
    - HAB_PLAN=graphite-web

script: test/full.sh
