#!/bin/sh

export pkg_origin="{{pkg.origin}}"
export pkg_name="{{pkg.name}}"
export pkg_path="{{pkg.path}}"
export pkg_svc_path="{{pkg.svc_path}}"
export pkg_svc_config_path="{{pkg.svc_config_path}}"
export pkg_svc_var_path="{{pkg.svc_var_path}}"
export pkg_svc_data_path="{{pkg.svc_data_path}}"
export pkg_svc_user="{{pkg.svc_user}}"
export pkg_svc_group="{{pkg.svc_group}}"
export cfg_system_file_limit="{{cfg.system.file_limit}}"
export cfg_cache_storage_dir="{{cfg.cache.storage_dir}}"
export cfg_cache_line_receiver_port="{{cfg.cache.line_receiver_port}}"
export cfg_cache_enable_udp_listener="{{cfg.cache.enable_udp_listener}}"
export cfg_cache_udp_receiver_port="{{cfg.cache.udp_receiver_port}}"
export cfg_cache_pickle_receiver_port="{{cfg.cache.pickle_receiver_port}}"
export cfg_cache_cache_query_port="{{cfg.cache.cache_query_port}}"
export carbon_pkg_path="{{pkgPathFor "socrata/carbon"}}"

{{pkgPathFor "socrata/inspec"}}/bin/inspec exec {{pkg.path}}/health \
  --vendor-cache={{pkg.svc_var_path}}/inspec/cache \
  --no-create-lockfile

if [ $? != 0 ]; then
  exit 2
else
  exit 0
fi
