#!/bin/sh

exec 2>&1

ulimit -n {{cfg.system.file_limit}}

# The build-index script in pre-1.0 graphite-web uses environment variables
# only and doesn't respect the settings in local_settings.py.
export GRAPHITE_ROOT="{{pkg.path}}"
export GRAPHITE_STORAGE_DIR="{{pkg.svc_data_path}}"
export WHISPER_DIR="{{bind.carbon-cache.first.cfg.storage_dir}}/whisper"

exec {{pkg.path}}/bin/uwsgi \
  --processes {{cfg.system.workers}} \
  {{#with bind.carbon-cache.first as |carbon| ~}}
  --carbon {{carbon.sys.ip}}:{{carbon.cfg.line_port}} \
  {{/with ~}}
  --pythonpath {{pkg.svc_config_path}} \
  --pythonpath {{pkg.path}}/lib \
  --pythonpath {{pkg.path}}/webapp/graphite \
  --wsgi-file {{pkg.svc_config_path}}/graphite.wsgi \
  --no-orphans \
  --master \
  --procname graphite-web \
  --die-on-term \
  --socket :{{cfg.system.port}}
