#!/bin/sh

exec 2>&1

ulimit -n {{cfg.system.file_limit}}

exec {{pkg.path}}/bin/uwsgi \
  --processes {{cfg.system.workers}} \
  {{#with bind.carbon_cache.first as |carbon| ~}}
  --carbon {{carbon.sys.ip}}:{{carbon.cfg.line_port}} \
  {{/with ~}}
  --pythonpath {{pkg.svc_config_path}} \
  --pythonpath {{pkg.path}}/lib \
  --pythonpath {{pkg.path}}/webapp/graphite \
  --wsgi-file {{pkg.svc_config_path}}/graphite.wsgi \
  --no-orphans \
  --master \
  --procname graphite-web \
  --die-on-term \
  --socket :{{cfg.system.port}}
  # TODO: Do we need these from the original runit service?
  # --uid {{pkg.svc_user}} \
  # --gid {{pkg.svc_group}} \
  # --chmod-socket 755 \

sleep 2
